#!/bin/bash

prefix=$1
sourceLanguage=$2
targetLanguage=$3

echo resources/$prefix-$targetLanguage.srt
if [ ! -s resources/$prefix-$targetLanguage.srt ]; then
    rm resources/$prefix-$targetLanguage.srt
fi
if [ ! -f resources/$prefix-$targetLanguage.srt ]; then
    if [ ! -s build/$prefix-$targetLanguage.vtt ]; then
        rm build/$prefix-$targetLanguage.vtt
    fi
    if [ ! -f build/$prefix-$targetLanguage.vtt ]; then
        echo Translating $prefix-$sourceLanguage.vtt to $targetLanguage
        python translate.py build/$prefix-$sourceLanguage.vtt $targetLanguage > build/$prefix-$targetLanguage.vtt
    fi
    python vtt2srt.py build/$prefix-$targetLanguage.vtt resources/$prefix-$targetLanguage.srt
fi
python3 subtitles.py $prefix $targetLanguage
