#!/bin/bash

episode=$1
paddedEpisode=`printf %03d $episode`
url=$2
targetName=osman-$paddedEpisode
mkdir -p build
if [ ! -f build/$targetName.vtt ]; then
    youtube-dl --all-subs --skip-download $url
    mv *\ Osman*\ $episode\.*.vtt build/$targetName-tr.vtt
fi
if [ ! -f build/$targetName.jpg ]; then
    youtube-dl --write-thumbnail --skip-download $url
    mv *\ Osman*\ $episode\.*.jpg build/$targetName.jpg
fi
#if [ ! -f build/$targetName.m4a ]; then
#    youtube-dl -f 140 $url
#    mv *\ Osman*\ $episode\.*.m4a build/$targetName.m4a
#fi
if [ ! -f build/$targetName.mp4 ]; then
    echo downloadVideo $url
    youtube-dl --rm-cache-dir
    youtube-dl -v $url
    
    if [ -f *\ Osman*\ $episode\.*.mp4 ]; then
        youtube-dl --rm-cache-dir
        youtube-dl -v $url
        if [ -f *\ Osman*\ $episode\.*.mp4 ]; then
            youtube-dl --rm-cache-dir
            youtube-dl -v $url
        fi
    fi
    mv *\ Osman*\ $episode\.*.mp4 build/$targetName.mp4
fi
