#!/bin/bash

echo download $1
if [ $1 == "osman" ]; then
    #./downloadVideo 89 https://www.youtube.com/watch?v=uPk856o66UM
    ./downloadVideo 90 https://www.youtube.com/watch?v=U-IsJHh9qik
    ./downloadVideo 91 https://www.youtube.com/watch?v=b7SZfclpHk4
fi
